version: "3.7"
services:
  db:
    image: mariadb:10.3
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: microblog
  api:
    build:
      context: ./backend
      target: dev
    command: sh -c "dockerize --wait tcp://db:3306 -timeout 30s && go run ./cmd/api/main.go"
    tty: true
    ports:
      - 8000:80
    volumes:
      - ./backend:/go/src
    environment:
      HTTP_PORT: 80
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: password
      DB_DATABASE: microblog
    depends_on:
      - db
volumes:
  db:
